osx_image: xcode11
language: objective-c

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -scheme units-swift-Package ONLY_ACTIVE_ARCH=NO | xcpretty

after_success:
- bash <(curl -s https://codecov.io/bash) -t 63842fcc-136e-4f2f-9255-cb71e3714a69
